# Data Collection/Cleaning/Preparation

## Collection

In [183]:
import numpy as np
import pandas as pd

In [184]:
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)

In [185]:
movies_df = pd.read_csv('./data/netflix.csv')

In [186]:
movies_df.head(10)

show_id     type                             title  \
0      s1    Movie              Dick Johnson Is Dead   
1      s2  TV Show                     Blood & Water   
2      s3  TV Show                         Ganglands   
3      s4  TV Show             Jailbirds New Orleans   
4      s5  TV Show                      Kota Factory   
5      s6  TV Show                     Midnight Mass   
6      s7    Movie  My Little Pony: A New Generation   
7      s8    Movie                           Sankofa   
8      s9  TV Show     The Great British Baking Show   
9     s10    Movie                      The Starling   

                        director  \
0                Kirsten Johnson   
1                            NaN   
2                Julien Leclercq   
3                            NaN   
4                            NaN   
5                  Mike Flanagan   
6  Robert Cullen, José Luis Ucha   
7                   Haile Gerima   
8                Andy Devonshire   
9                 Theodore Melfi   

                                                cast  \
0                                                NaN   
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...   
3                                                NaN   
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...   
5  Kate Siegel, Zach Gilford, Hamish Linklater, H...   
6  Vanessa Hudgens, Kimiko Glenn, James Marsden, ...   
7  Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...   
8  Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...   
9  Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...   

                                             country          date_added  \
0                                      United States  September 25, 2021   
1                                       South Africa  September 24, 2021   
2                                                NaN  September 24, 2021   
3                                                NaN  September 24, 2021   
4                                              India  September 24, 2021   
5                                                NaN  September 24, 2021   
6                                                NaN  September 24, 2021   
7  United States, Ghana, Burkina Faso, United Kin...  September 24, 2021   
8                                     United Kingdom  September 24, 2021   
9                                      United States  September 24, 2021   

   release_year rating   duration  \
0          2020  PG-13     90 min   
1          2021  TV-MA  2 Seasons   
2          2021  TV-MA   1 Season   
3          2021  TV-MA   1 Season   
4          2021  TV-MA  2 Seasons   
5          2021  TV-MA   1 Season   
6          2021     PG     91 min   
7          1993  TV-MA    125 min   
8          2021  TV-14  9 Seasons   
9          2021  PG-13    104 min   

                                           listed_in  \
0                                      Documentaries   
1    International TV Shows, TV Dramas, TV Mysteries   
2  Crime TV Shows, International TV Shows, TV Act...   
3                             Docuseries, Reality TV   
4  International TV Shows, Romantic TV Shows, TV ...   
5                 TV Dramas, TV Horror, TV Mysteries   
6                           Children & Family Movies   
7   Dramas, Independent Movies, International Movies   
8                       British TV Shows, Reality TV   
9                                   Comedies, Dramas   

                                         description  
0  As her father nears the end of his life, filmm...  
1  After crossing paths at a party, a Cape Town t...  
2  To protect his family from a powerful drug lor...  
3  Feuds, flirtations and toilet talk go down amo...  
4  In a city of coaching centers known to train I...  
5  The arrival of a charismatic young priest brin...  
6  Equestria's divided. But a bright-eyed hero be...  
7  On a photo shoot in Ghana, an American model s...  
8  A talented 

## Cleaning

In [187]:
movies_df.shape

(8807, 12)

In [188]:
movies_df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [189]:
movies_df.dropna(inplace=True)

In [190]:
movies_df.shape

(5332, 12)

In [191]:
movies_df.duplicated().sum()

0

In [192]:
movies_df.iloc[0]

show_id                                                        s8
type                                                        Movie
title                                                     Sankofa
director                                             Haile Gerima
cast            Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...
country         United States, Ghana, Burkina Faso, United Kin...
date_added                                     September 24, 2021
release_year                                                 1993
rating                                                      TV-MA
duration                                                  125 min
listed_in        Dramas, Independent Movies, International Movies
description     On a photo shoot in Ghana, an American model s...
Name: 7, dtype: object

## Preparation

In [193]:
movies_df = movies_df[['show_id','type','title','director','cast','listed_in','description']]

In [194]:
movies_df.head(10)

show_id     type                          title             director  \
7       s8    Movie                        Sankofa         Haile Gerima   
8       s9  TV Show  The Great British Baking Show      Andy Devonshire   
9      s10    Movie                   The Starling       Theodore Melfi   
12     s13    Movie                   Je Suis Karl  Christian Schwochow   
24     s25    Movie                          Jeans           S. Shankar   
27     s28    Movie                      Grown Ups         Dennis Dugan   
28     s29    Movie                     Dark Skies        Scott Stewart   
29     s30    Movie                       Paranoia       Robert Luketic   
38     s39    Movie            Birth of the Dragon         George Nolfi   
41     s42    Movie                           Jaws     Steven Spielberg   

                                                 cast  \
7   Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...   
8   Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...   
9   Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...   
12  Luna Wedler, Jannis Niewöhner, Milan Peschel, ...   
24  Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...   
27  Adam Sandler, Kevin James, Chris Rock, David S...   
28  Keri Russell, Josh Hamilton, J.K. Simmons, Dak...   
29  Liam Hemsworth, Gary Oldman, Amber Heard, Harr...   
38  Billy Magnussen, Ron Yuan, Qu Jingjing, Terry ...   
41  Roy Scheider, Robert Shaw, Richard Dreyfuss, L...   

                                           listed_in  \
7   Dramas, Independent Movies, International Movies   
8                       British TV Shows, Reality TV   
9                                   Comedies, Dramas   
12                      Dramas, International Movies   
24   Comedies, International Movies, Romantic Movies   
27                                          Comedies   
28                   Horror Movies, Sci-Fi & Fantasy   
29                                         Thrillers   
38                        Action & Adventure, Dramas   
41        Action & Adventure, Classic Movies, Dramas   

                                          description  
7   On a photo shoot in Ghana, an American model s...  
8   A talented batch of amateur bakers face off in...  
9   A woman adjusting to life after a loss contend...  
12  After most of her family is murdered in a terr...  
24  When the father of the man she loves insists t...  
27  Mourning the loss of their beloved junior high...  
28  A family’s idyllic suburban life shatters when...  
29  Blackmailed by his company's CEO, a low-level ...  
38  A young Bruce Lee angers kung fu traditionalis...  
41  When an insatiable great white shark terrorize...

# Machine Learning

## Installations

In [195]:
from sklearn.feature_extraction.text import CountVectorizer
import nltk
from nltk.stem.porter import PorterStemmer
from sklearn.metrics.pairwise import cosine_similarity

## Feature Extraction

In [196]:
cv = CountVectorizer(max_features=50000,stop_words='english')

In [197]:
cv.fit_transform(movies_df['description']).toarray().shape

(5332, 14298)

In [198]:
vectors = cv.fit_transform(movies_df['description']).toarray()

In [199]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [200]:
ps = PorterStemmer()

In [201]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [202]:
movies_df['description'] = movies_df['description'].apply(stem)

In [203]:
cosine_similarity(vectors)

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.07412493],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.07412493, 0.07412493,
        0.07692308],
       ...,
       [0.        , 0.        , 0.07412493, ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.07412493, ..., 0.        , 1.        ,
        0.        ],
       [0.07412493, 0.        , 0.07692308, ..., 0.        , 0.        ,
        1.        ]])

In [204]:
cosine_similarity(vectors).shape

(5332, 5332)

In [205]:
similarity = cosine_similarity(vectors)

In [206]:
similarity[0]

array([1.        , 0.        , 0.        , ..., 0.        , 0.        ,
       0.07412493])

In [207]:
similarity.shape

(5332, 5332)

In [208]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])[1:6]

[(4733, 0.14824986333222026),
 (2768, 0.14285714285714288),
 (2048, 0.13801311186847084),
 (937, 0.1336306209562122),
 (1962, 0.1336306209562122)]

## Recommender

In [230]:
def recommend(movies_df,film_type, movie):
    movie_index = movies_df[movies_df['title']==movie].index[0]
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]
    
    for i in movie_list:
        if film_type == 'movie':
            if movies_df.iloc[i[0]].type == 'Movie':
                print(movies_df.iloc[i[0]].title)
        else:
            if movies_df.iloc[i[0]].type == 'TV Show':
                print(movies_df.iloc[i[0]].title)

In [232]:
recommend(movies_df,'movie','House Party')

Lalbaug Parel: Zali Mumbai Sonyachi
The Girl and the Gun
May You Prosper
Buddies
Project Marathwada


## Testing